import type { Ruleset } from '../engine';

export const VALUES: Record<string, Partial<Record<Ruleset, number>> & { base: number }> = {
  chickenHand: { base: 1, riichi: 0, 'chinese-official': 0 },
  selfDraw: { base: 1, 'chinese-official': 1, riichi: 1 },
  replacementWin: { base: 1 },
  lastTileWin: { base: 1 },
  rinshanKaihou: { base: 0, riichi: 1 },
  robbingKong: { base: 1, 'chinese-official': 8, riichi: 1 },
  // MCR win-condition fans. Riichi keeps its own haitei / houtei / rinshan
  // entries above, so these stay MCR-only rather than being shared.
  lastTileDraw: { base: 0, 'chinese-official': 8 },
  lastTileClaim: { base: 0, 'chinese-official': 8 },
  outWithReplacement: { base: 0, 'chinese-official': 8 },
  lastTile: { base: 0, 'chinese-official': 4 },
  edgeWait: { base: 0, 'chinese-official': 1 },
  closedWait: { base: 0, 'chinese-official': 1 },
  singleWait: { base: 0, 'chinese-official': 1 },
  // MCR counts Kongs by concealment; Riichi's sankantsu / suukantsu are
  // separate entries so the two ladders never mix.
  meldedKong: { base: 0, 'chinese-official': 1 },
  concealedKong: { base: 0, 'chinese-official': 2 },
  twoMeldedKongs: { base: 0, 'chinese-official': 4 },
  twoConcealedKongs: { base: 0, 'chinese-official': 8 },
  threeKongs: { base: 0, 'chinese-official': 32 },
  fourKongs: { base: 0, 'chinese-official': 88 },
  riichi: { base: 0, riichi: 1 },
  doubleRiichi: { base: 0, riichi: 2 },
  ippatsu: { base: 0, riichi: 1 },
  haiteiRaoyue: { base: 0, riichi: 1 },
  houteiRaoyui: { base: 0, riichi: 1 },
  pinfu: { base: 0, riichi: 1 },
  iipeikou: { base: 0, riichi: 1 },
  ryanpeikou: { base: 0, riichi: 3 },
  ittsuu: { base: 0, riichi: 2 },
  sanshokuDoujun: { base: 0, riichi: 2 },
  sanshokuDoukou: { base: 0, riichi: 2 },
  chanta: { base: 0, riichi: 2 },
  junchan: { base: 0, riichi: 3 },
  honroutou: { base: 0, riichi: 2 },
  sanankou: { base: 0, riichi: 2 },
  sankantsu: { base: 0, riichi: 2 },
  smallFourWinds: { base: 10, 'chinese-official': 64, riichi: 13 },
  bigFourWinds: { base: 10, 'chinese-official': 88, riichi: 13 },
  allTerminals: { base: 10, 'chinese-official': 64, riichi: 13 },
  allGreen: { base: 0, 'chinese-official': 88, riichi: 13 },
  fourKans: { base: 0, riichi: 13 },
  concealed: { base: 1, 'chinese-official': 2, riichi: 1 },
  allSimples: { base: 1, 'chinese-official': 2, riichi: 1 },
  allSequences: { base: 1, 'chinese-official': 2, riichi: 1 },
  dragonTriplet: { base: 1, 'chinese-official': 2, riichi: 1 },
  seatWind: { base: 1, 'chinese-official': 2, riichi: 1 },
  roundWind: { base: 1, 'chinese-official': 2, riichi: 1 },
  allTriplets: { base: 3, 'chinese-official': 6, riichi: 2 },
  pureStraight: { base: 0, 'chinese-official': 16 },
  mixedTripleChow: { base: 0, 'chinese-official': 8 },
  mixedShiftedChows: { base: 0, 'chinese-official': 6 },
  triplePung: { base: 0, 'chinese-official': 16 },
  pureTripleChow: { base: 0, 'chinese-official': 24 },
  pureDoubleChow: { base: 0, 'chinese-official': 1 },
  mixedDoubleChow: { base: 0, 'chinese-official': 1 },
  shortStraight: { base: 0, 'chinese-official': 1 },
  doublePungs: { base: 0, 'chinese-official': 2 },
  pungTerminalsHonours: { base: 0, 'chinese-official': 1 },
  threeConcealedPungs: { base: 0, 'chinese-official': 16 },
  twoConcealedPungs: { base: 0, 'chinese-official': 2 },
  allTypes: { base: 0, 'chinese-official': 6 },
  oneVoidedSuit: { base: 0, 'chinese-official': 1 },
  noHonours: { base: 0, 'chinese-official': 1 },
  outsideHand: { base: 0, 'chinese-official': 4 },
  bigThreeWinds: { base: 0, 'chinese-official': 12 },
  twoDragonPungs: { base: 0, 'chinese-official': 6 },
  allFives: { base: 0, 'chinese-official': 16 },
  upperFour: { base: 0, 'chinese-official': 12 },
  lowerFour: { base: 0, 'chinese-official': 12 },
  mixedStraight: { base: 0, 'chinese-official': 8 },
  reversibleTiles: { base: 0, 'chinese-official': 8 },
  mixedShiftedPungs: { base: 0, 'chinese-official': 8 },
  tileHog: { base: 0, 'chinese-official': 2 },
  meldedHand: { base: 0, 'chinese-official': 6 },
  twoTerminalChows: { base: 0, 'chinese-official': 1 },
  threeSuitedTerminalChows: { base: 0, 'chinese-official': 16 },
  pureTerminalChows: { base: 0, 'chinese-official': 64 },
  sevenShiftedPairs: { base: 0, 'chinese-official': 88 },
  /** MCR scores a legal hand that reaches eight points with no other fan. */
  mcrChickenHand: { base: 0, 'chinese-official': 8 },
  quadrupleChow: { base: 0, 'chinese-official': 48 },
  fourShiftedPungs: { base: 0, 'chinese-official': 48 },
  fourShiftedChows: { base: 0, 'chinese-official': 32 },
  allEvenPungs: { base: 0, 'chinese-official': 24 },
  pureShiftedPungs: { base: 0, 'chinese-official': 24 },
  pureShiftedChows: { base: 0, 'chinese-official': 16 },
  upperTiles: { base: 0, 'chinese-official': 24 },
  middleTiles: { base: 0, 'chinese-official': 24 },
  lowerTiles: { base: 0, 'chinese-official': 24 },
  halfFlush: { base: 3, 'chinese-official': 6, riichi: 2 },
  sevenPairs: { base: 4, 'chinese-official': 24, riichi: 2 },
  littleThreeDragons: { base: 5, 'chinese-official': 64, riichi: 2 },
  fullyConcealed: { base: 0, 'chinese-official': 4 },
  fullFlush: { base: 7, 'chinese-official': 24, riichi: 6 },
  allTerminalsHonours: { base: 1, 'chinese-official': 32, riichi: 13 },
  allHonours: { base: 10, 'chinese-official': 64, riichi: 13 },
  bigThreeDragons: { base: 8, 'chinese-official': 88, riichi: 13 },
  fourConcealedTriplets: { base: 10, 'chinese-official': 64, riichi: 13 },
  thirteenOrphans: { base: 10, 'chinese-official': 88, riichi: 13 },
  nineGates: { base: 0, 'chinese-official': 88, riichi: 13 },
  heavenlyHand: { base: 0, riichi: 13 },
  earthlyHand: { base: 0, riichi: 13 },
  renhou: { base: 0, riichi: 5 }
};

export const LIMIT: Record<Ruleset, number> = {
  hongkong: 10,
  riichi: 13,
  'chinese-official': 88
};

export function value(id: keyof typeof VALUES, ruleset: Ruleset): number {
  const entry = VALUES[id];
  return entry[ruleset] ?? entry.base;
}

export type ValueId = keyof typeof VALUES;
